spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/complaint_user_service
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      maximum-pool-size: 50
      connection-test-query: SELECT 1
      connection-timeout: 30000
      idle-timeout: 30000
      max-lifetime: 1800000
      validation-timeout: 1000
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  application:
    name: User-Service

  servlet:
    multipart:
      max-file-size: 15GB
      max-request-size: 15GB
  mvc:
    pathmatch:
      matching-strategy : ANT_PATH_MATCHER
  sql:
    init:
      mode: always

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
logging:
  file:
    name: logs/app.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS Z,Asia/Kolkata} %-5level %logger : %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS Z,Asia/Kolkata} %-5level [%thread] %logger : %msg%n"
  rollingPolicy:
    type: timeBased
    fileNamePattern: "logs/app-%d{yyyy-MM-dd}.log"
    maxHistory: 7
  level:
    com.caged.userservice.: DEBUG

application:
  security:
    jwt:
      secret-key: 4B6C334B6175474A4C564F446D386B726D5378514D6A3778584F647362634C79
      expiration: 86400000 # a day
      jwtExpirationInMs: 86400000
      refreshTokenExpirationInMs: 172800000

cors:
  origins: "http://localhost:3000"


springdoc:
  packagesToScan: com.caged.userservice.controller
  pathsToMatch: /auth/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30

server:
  port: 8080