server:
  port: 8085

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: true

spring:
  application:
    name: Eureka-Discovery